### ISSUE TITLE
LLVM ERROR: Cannot select: 0x7fae936b8610: f32 = X86ISD::FSETCCss 0x7fae937b1410, 0x7fae936da710, 0x7fae936ba410 [ORD=344] [ID=9]

### ISSUE THREAD

**Issue by wanlipeng** [DavHoffmann/Multi-humanDataGeneration#4]
Excuse me, I encountered this problem when running the code to generate optical flow. What can cause it?
------------------------------------------------------------------------------------------------------------------------------
In function: _ZN11OpenImageIO4v1_713fast_safe_powEff
LLVM ERROR: Cannot select: 0x7fae936b8610: f32 = X86ISD::FSETCCss 0x7fae937b1410, 0x7fae936da710, 0x7fae936ba410 [ORD=344] [ID=9]
  0x7fae937b1410: f32,ch = CopyFromReg 0x7fae9365ec38, 0x7fae936b8510 [ORD=343] [ID=6]
    0x7fae936b8510: f32 = Register %vreg8 [ID=1]
  0x7fae936da710: f32,ch = load 0x7fae9365ec38, 0x7fae937b6810, 0x7fae937b8d10<LD4[ConstantPool]> [ID=8]
    0x7fae937b6810: i64 = X86ISD::Wrapper 0x7fae9371c410 [ID=7]
      0x7fae9371c410: i64 = TargetConstantPool<float 1.260000e+02> 0 [ID=5]
    0x7fae937b8d10: i64 = undef [ID=4]
  0x7fae936ba410: i8 = Constant<6> [ID=3]
In function: _ZN11OpenImageIO4v1_713fast_safe_powEff

**Comment by DavHoffmann** [comment]
Hi Wanlipeng,

thanks for your interest in this project. 

This error does not look like it's thrown by my code, but rather looks like a Blender problem. Which Blender version are you using? Can you use the Blender GUI and render images here without any errors? You might also consider to set up blender in a new and clean environment. For instance this [thread](https://blenderartists.org/t/blender-crashes-at-startup-with-llvm-error/697803) reports a similar problem and finds that multiple installations of OpenCL caused the issue.

**Comment by wanlipeng** [comment]
Thank you very much for your reply, it gives me a lot of hope!!
The environment in which I currently run the code is as follows:

- ubuntu 20.04.4 LTS

- python3.8(collisionCheck)

- blender-2.79b-linux-glibc219-x86_64

- ldd (Ubuntu GLIBC 2.31-0ubuntu9.9) 2.31

I am using the version of blender you recommended, but I am running an ubuntu20 system. I checked that the installed blender depends on the glibc2.19 version. I wonder if this problem is caused.

**Comment by wanlipeng** [comment]
@DavHoffmann  I tried to randomly render a photo and then saved it. The result was okey. I looked at blender to see if it was okay?? Could you please help me What caused the error in the above synthetic optical flow picture?
---------------------------------------------------------------
The random rendering test code is as follows：
import bpy
import random
from mathutils import Vector
# 删除默认的立方体
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_by_type(type='MESH')
bpy.ops.object.delete()
# 随机生成一个位置
location = Vector((random.uniform(-5, 5), random.uniform(-5, 5), random.uniform(0, 5)))
# 添加一个新的立方体
bpy.ops.mesh.primitive_cube_add(location=location)
# 设置渲染参数
bpy.context.scene.render.image_settings.file_format = 'PNG'
bpy.context.scene.render.filepath = './output_render_test.png'
# 渲染图片
bpy.ops.render.render(write_still=True)

**Comment by wanlipeng** [comment]
@DavHoffmann I tried to randomly render a photo and then saved it. The result was okey. I looked at blender to see if it was okay?? Could you please help me What caused the error in the above synthetic optical flow picture?
-------------------------------------------------------------
The random rendering test code is as follows:

import bpy
import random
from mathutils import Vector
bpy.ops.object.select_all(action='DESELECT')
bpy.ops.object.select_by_type(type='MESH')
bpy.ops.object.delete()
location = Vector((random.uniform(-5, 5), random.uniform(-5, 5), random.uniform(0, 5)))
bpy.ops.mesh.primitive_cube_add(location=location)
bpy.context.scene.render.image_settings.file_format = 'PNG'
bpy.context.scene.render.filepath = './output_render_test.png'
bpy.ops.render.render(write_still=True)

**Comment by wanlipeng** [comment]
@DavHoffmann  When I debug, the problem occurs in this line and an error is reported， 
`bpy.ops.render.render(write_still=True)`

**Comment by wanlipeng** [comment]
@DavHoffmann Hello, I reconfigured an environment in ubuntu18.04 today, but errors still occurred during operation. Can you please send me the configuration environment for running for reference?
---------------------------------------
VERSION="18.04.6 LTS (Bionic Beaver)"
blender-2.79b-linux-glibc219-x86_64
Python 3.6.10(collisionCheck)
ldd (Ubuntu GLIBC 2.27-3ubuntu1.6) 2.27
---------------------------------------------
LLVM ERROR: Cannot select: 0x7fe8104bb610: f32 = X86ISD::FSETCCss 0x7fe8105b4410, 0x7fe8105f1710, 0x7fe8104bd410 [ORD=344] [ID=9]
  0x7fe8105b4410: f32,ch = CopyFromReg 0x7fe81045ec38, 0x7fe8104bb510 [ORD=343] [ID=6]
    0x7fe8104bb510: f32 = Register %vreg8 [ID=1]
  0x7fe8105f1710: f32,ch = load 0x7fe81045ec38, 0x7fe8105b9810, 0x7fe8105bbd10<LD4[ConstantPool]> [ID=8]
    0x7fe8105b9810: i64 = X86ISD::Wrapper 0x7fe81051f410 [ID=7]
      0x7fe81051f410: i64 = TargetConstantPool<float 1.260000e+02> 0 [ID=5]
    0x7fe8105bbd10: i64 = undef [ID=4]
  0x7fe8104bd410: i8 = Constant<6> [ID=3]
In function: _ZN11OpenImageIO4v1_713fast_safe_powEff
LLVM ERROR: Cannot select: 0x7fe80c6b8610: f32 = X86ISD::FSETCCss 0x7fe80c7b1410, 0x7fe80c6da710, 0x7fe80c6ba410 [ORD=344] [ID=9]
  0x7fe80c7b1410: f32,ch = CopyFromReg 0x7fe80c65ec38, 0x7fe80c6b8510 [ORD=343] [ID=6]
    0x7fe80c6b8510: f32 = Register %vreg8 [ID=1]
  0x7fe80c6da710: f32,ch = load 0x7fe80c65ec38, 0x7fe80c7b6810, 0x7fe80c7b8d10<LD4[ConstantPool]> [ID=8]
    0x7fe80c7b6810: i64 = X86ISD::Wrapper 0x7fe80c71c410 [ID=7]
      0x7fe80c71c410: i64 = TargetConstantPool<float 1.260000e+02> 0 [ID=5]
    0x7fe80c7b8d10: i64 = undef [ID=4]
  0x7fe80c6ba410: i8 = Constant<6> [ID=3]
In function: _ZN11OpenImageIO4v1_713fast_safe_powEff
